#!/usr/bin/env bash

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

log "SET TUB MAT:"

mat=$(jq -r ".tub_mat | values" "$CONFIG_FILE")
mat=$(echo "$mat"*10^25 | bc -l)
mat=$(seth --to-uint256 "${mat%.*}")
sethSend "$SAI_MOM" 'setMat(uint256)' "$mat"
